export const SET_USER_AUTHENTICATED = 'SET_USER_AUTHENTICATED';
export const SET_USER_UNAUTHENTICATED = 'SET_USER_UNAUTHENTICATED';
export const SET_REQUEST_RUNNING = 'SET_REQ_RUN';
export const SET_REQUEST_DONE = 'SET_REQ_DONE';
export const SET_REQUEST_ERROR = 'SET_REQ_ERR';
